import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import SplashCursor from "@/Reactbits/SplashCursor/SplashCursor";
import ScrollTop from "@/components/ScrollTop";
import FooterWrapper from "@/components/FooterWrapper";
import { Toaster } from "react-hot-toast";
import NavbarWrapper from "@/components/NavbarWrapper";
import { AuthProvider } from "@/contexts/AuthContext";
import { ProductProvider } from "@/contexts/ProductContext";
import ChatbotIcon from "./components/ChatbotIcon";
import LocomotiveProvider from "@/components/LocomotiveProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fofood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* <SplashCursor /> */}
        <Toaster />
        <ScrollTop />
        <ProductProvider>
          <AuthProvider>
            <LocomotiveProvider>
              <NavbarWrapper />
              <ChatbotIcon />
              <main className="flex-grow bg-white text-black">{children}</main>
              <FooterWrapper />
            </LocomotiveProvider>
          </AuthProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
